package com.qbryx.tommystore.enums;

public enum AdminPage {
	DASHBOARD,
	USER_LIST,
	ADD_ADMINISTRATOR,
	ADD_CATEGORY,
	VIEW_CATEGORY,
	UPDATE_CATEGORY,
	ADD_PRODUCT,
	UPDATE_PRODUCT,
	VIEW_PRODUCT,
	UPDATE_INVENTORY,
	VIEW_INVENTORY_HISTORY
	;
}
